### ISSUE TITLE
Creation of build artifacts triggers full rebuild of project

### ISSUE THREAD

**Issue by IESE-T3** [DeHecht/cmake-eclipse-helper#6]
Hi,

great plugin, but there is one problem occuring during our builds with it:

Whenever a new artifact gets created inside the buildtree (as in, a new executable file is generated by the compiler) the root CMakelists.txt gets touched by the plugin, which triggers a full rebuild of the project, when trying to run the built executable or trying to build something else again.
In our case this is really time consuming and might even stop us from executing/debugging files, if during the triggered full rebuild some projects exist, which fail to compile.

Would it be possible to add an option to disable the touching feature or make it ignore the bin/ (or other named CMake build directory), Binaries and Archives directories?

**Comment by DeHecht** [comment]
Hello,

great idea. I will add the option to disable the touching handling. Skipping the CMake build directory sound like a good plan, so this will be added, too!

I have it running on my eclipse already. I hope to be able to release it this weekend.

Just a few questions out of curiosity:

- can you give me a rough impression how one of your project is organized (because you mentioned binary and archive directories)
- do you use FILE(GLOB …) for source files within your project?

**Comment by DeHecht** [comment]
I did some testing this weekend and have already uploaded a new plugin version. I don't expect any issues, but I will ask some of my colleagues to probe this version. In the future I will create a "development" update site for this... but it seemed urgent for you, so I didn't want to let you down.

**Comment by IESE-T3** [comment]
Hi,

sorry for the late reply, and wow, thanks for the fast update!
Just tested the new version on our end and everything is working flawlessly.

Regarding your questions:

- Our project organization is rather straightforward with add_executable(...) and add_library(...) calls. I was referring to the Binaries and Archives directories in the Project Explorer in Eclipse, which aren't "real" directories per se, but rather virtual folders listing the built binary/library files in the project. But it seems like ignoring the CMake build directory already did the trick, so no special handling needed there.
- We list our sources explicitly through target_sources(..), so no globbing for us.

Thanks again!

**Comment by DeHecht** [comment]
Hi,

excellent! We also didn't notice any issues today.

Based on your answer I would suggest you to disable the "touching" completely within the settings as this is only useful when using FILE globbing. We use that in our company excessively (although discouraged by CMake itself). We are too lazy to add/remove the files in add_executable and add_library and target_sources was not available at the time.

Thanks for filing a issue :+1:
